use_small_heuristics = "Max"
wrap_comments = false
fn_single_line = true
imports_granularity = "Crate"
reorder_impl_items = true
spaces_around_ranges = false
struct_field_align_threshold = 40
struct_lit_single_line = true
use_field_init_shorthand = true
unstable_features = true
max_width = 90
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
condense_wildcard_suffixes = true
fn_params_layout = "Compressed"
group_imports = "One"
